# These are supported funding model platforms

github:  e.g., [@subolshop, fatidelfat@gmail.com]
ko_fi:e.g., https://ko-fi/thyka
custom:  e.g., ['https://degeloper.facebook.com', 'https://facebook.com/klikshop01']
